namespace Backend.Utils.Enums
{
	public enum InventoryType
	{
		PLAYER,
		VEHICLE_TRUNK,
		VEHICLE_GLOVEBOX,
		DROP_BOX_1,
		DROP_BOX_2,
		DROP_BOX_3,
		TEAM,
		STORAGE,
		BANK_ROBBERY_LOOT,
		JEWELERY_LOOT,
		LABORATORY_INPUT,
		LABORATORY_OUTPUT,
		LABORATORY_FUEL,
		LABORATORY_ROB,
		HOUSE_INVENTORY
	}
}